---
linters:
    flake8:
    eslint:
        config: './eslint.config'
    csslint:
        ignore: 'box-model,box-sizing,ids'

files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'